# Emacs Plus build configuration
# See: https://github.com/d12frosted/homebrew-emacs-plus

# Apply performance and feature patches
patches:
  - aggressive-read-buffering
  - frame-transparency
  - mac-font-use-typo-metrics

# macOS Tahoe-compliant liquid glass icon
icon: liquid-glass
