abbr -a -- gg 'git status'
abbr -a -- gd 'git diff'
abbr -a -- gl 'git pull'
abbr -a -- gf 'git fetch'
abbr -a -- gr 'git rebase'
abbr -a -- gra 'git rebase --abort'
abbr -a -- grc 'git rebase --continue'
abbr -a -- gm 'git merge'
abbr -a -- gs 'git show --ext-diff'
abbr -a -- ga 'git add'
abbr -a -- ga. 'git add .'
abbr -a -- gaa 'git add --all'
abbr -a -- gc 'git commit'
abbr -a -- gca 'git commit --amend'
abbr -a -- gcan 'git commit --amend --no-edit'
abbr -a -- gp 'git push'
abbr -a -- gp! 'git push --force-with-lease'
abbr -a --set-cursor='%' -- gcm 'git commit -m "%"'
