palette = "catppuccin_frappe"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$cmd_duration\
$ruby\
$golang\
$nodejs\
$python\
$rust\
$elixir\
$java\
$deno\
$bun\
$line_break\
$character"""

command_timeout = 650

[directory]
style = "bold lavender"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold mauve"

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "

[ruby]
format = "[$symbol ($version )]($style)"
detect_files = ["Gemfile", "*.rb", ".ruby-version", "Rakefile", "*.gemspec"]
detect_folders = []

[golang]
format = "[$symbol ($version )]($style)"
detect_files = ["go.mod", "go.sum", "*.go", "go.work"]
detect_folders = ["vendor"]

[nodejs]
format = "[$symbol ($version )]($style)"
detect_files = ["package.json", "*.js", "*.ts", "*.jsx", "*.tsx", ".node-version", ".nvmrc"]
detect_folders = ["node_modules"]

[python]
format = "[$symbol ($version )]($style)"
detect_files = ["requirements.txt", "pyproject.toml", "*.py", "Pipfile", "tox.ini", "setup.py", "setup.cfg", ".python-version"]
detect_folders = [".venv", "venv", ".virtualenv", "__pycache__"]

[rust]
format = "[$symbol ($version )]($style)"
detect_files = ["Cargo.toml", "*.rs"]
detect_folders = ["target"]

[elixir]
format = "[$symbol ($version )]($style)"
detect_files = ["mix.exs", "*.ex", "*.exs", "*.eex", "*.leex", "*.heex"]
detect_folders = ["_build", "deps"]

[java]
format = "[$symbol ($version )]($style)"
detect_files = ["pom.xml", "build.gradle", "build.gradle.kts", "*.java", "*.class", "*.jar", ".java-version"]
detect_folders = [".gradle", ".mvn"]

[deno]
format = "[$symbol ($version )]($style)"
detect_files = ["deno.json", "deno.jsonc", "deno.lock", "*.ts", "*.tsx"]
detect_folders = []

[bun]
format = "[$symbol ($version )]($style)"
detect_files = ["bun.lockb", "bunfig.toml", "*.bun.ts", "*.bun.js"]
detect_folders = []

# https://github.com/catppuccin/starship/blob/main/themes/frappe.toml
[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
