palette = "catppuccin_frappe"

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$cmd_duration\
$ruby\
$golang\
$nodejs\
$python\
$line_break\
$character"""

command_timeout = 650

[directory]
style = "bold lavender"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold mauve"

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "

[ruby]
format = "[$symbol ($version )]($style)"

[golang]
format = "[$symbol ($version )]($style)"

[nodejs]
format = "[$symbol ($version )]($style)"

# https://github.com/catppuccin/starship/blob/main/themes/frappe.toml
[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
