format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$cmd_duration\
$line_break\
$python\
$character"""

right_format = """
$ruby\
$golang\
$nodejs
"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "

[ruby]
format = "[$symbol ($version )]($style)"

[golang]
format = "[$symbol ($version )]($style)"

[nodejs]
format = "[$symbol ($version )]($style)"
